package dev.droidshield.gradleplugin

import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction

/**
 * Writes a single generated Kotlin file exposing this build's polymorphic
 * seed as a compile-time constant. See DECISIONS.md D026 for why this
 * source-codegen approach was chosen over ASM bytecode instrumentation of
 * host-app classes.
 */
abstract class GenerateDroidShieldSeedTask : DefaultTask() {

    @get:Input
    abstract val seed: Property<Long>

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        val packageDir = outputDir.get().asFile.resolve("dev/droidshield/generated")
        packageDir.mkdirs()

        val seedValue = seed.get()
        val file = packageDir.resolve("DroidShieldBuildSeed.kt")
        file.writeText(
            """
            // Generated by droidshield-gradle-plugin. Do not edit — this
            // file is overwritten on every build. See DECISIONS.md D026.
            package dev.droidshield.generated

            object DroidShieldBuildSeed {
                const val SEED: Long = ${seedValue}L
            }
            """.trimIndent() + "\n",
        )
    }
}
