package dev.droidshield.engine

import dev.droidshield.domain.ThreatCheck
import kotlin.random.Random

/**
 * The polymorphic-injection mechanism (ARCHITECTURE.md §1/§8): each build
 * gets a different ordering/subset of checks so a bypass tuned against one
 * build's check sequence doesn't trivially transfer to the next.
 *
 * This governs *execution order and subset selection at runtime*, given
 * whatever seed the build produced. See DECISIONS.md D026 for why build-time
 * *variance* is generated by `droidshield-gradle-plugin` as a source-codegen
 * seed rather than ASM bytecode rewriting.
 */
sealed class CheckOrder {

    abstract fun apply(checks: Set<ThreatCheck>): List<ThreatCheck>

    /** Deterministic declaration order — useful for tests and debugging. */
    object Unseeded : CheckOrder() {
        override fun apply(checks: Set<ThreatCheck>): List<ThreatCheck> = checks.toList()
    }

    /**
     * Shuffles check order using [seed], and optionally drops down to
     * [subsetFraction] of the checks (still always running at least one
     * check per category present in the input set, so no category goes
     * completely unchecked in a given build).
     */
    class Seeded(
        private val seed: Long,
        private val subsetFraction: Double = 1.0,
    ) : CheckOrder() {

        init {
            require(subsetFraction in 0.0..1.0) { "subsetFraction must be in [0.0, 1.0], was $subsetFraction" }
        }

        override fun apply(checks: Set<ThreatCheck>): List<ThreatCheck> {
            val random = Random(seed)
            val shuffled = checks.shuffled(random)

            if (subsetFraction >= 1.0) return shuffled

            val byCategory = shuffled.groupBy { it.category }
            val guaranteed = byCategory.values.map { it.first() }.toSet()

            val targetSize = (shuffled.size * subsetFraction).toInt().coerceAtLeast(guaranteed.size)
            val remainder = shuffled.filterNot { it in guaranteed }
            val extra = remainder.take((targetSize - guaranteed.size).coerceAtLeast(0))

            return (guaranteed + extra).shuffled(random)
        }
    }
}
